
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd4\x8fZ\x84#\x11\x98\x03T\xdb\xc6\x05\x84!\xac}'
    
_lr_action_items = {'BAR':([2,3,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[7,12,-17,-16,-15,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,7,-18,-11,]),'RPAREN':([3,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[19,-17,-16,-15,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,22,-18,-11,]),'QUESTION':([2,3,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[9,13,-17,-16,9,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,9,9,-11,]),'BACKSLASH':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[3,3,14,3,-17,-16,3,3,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,3,3,-11,]),'STAR':([2,3,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[11,17,-17,-16,11,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,11,11,-11,]),'PLUS':([2,3,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[10,15,-17,-16,10,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,10,10,-11,]),'LPAREN':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[4,4,16,4,-17,-16,4,-15,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,4,-18,-11,]),'ALPHA':([0,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[5,5,5,-17,-16,5,-15,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,5,5,-11,]),'DOT':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[6,6,18,6,-17,-16,6,-15,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,6,6,-11,]),'$end':([0,1,2,5,6,8,9,10,11,12,13,14,15,16,17,18,19,21,22,],[-2,0,-1,-17,-16,-15,-14,-13,-12,-7,-6,-10,-5,-8,-4,-3,-9,-18,-11,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'regex':([0,],[1,]),'expr':([0,2,4,7,8,20,21,],[2,8,20,21,8,8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> regex","S'",1,None,None,None),
  ('regex -> expr','regex',1,'p_regex_expr','/Users/seojunkyo/Desktop/automata/regex.py',53),
  ('regex -> <empty>','regex',0,'p_regex_empty','/Users/seojunkyo/Desktop/automata/regex.py',58),
  ('expr -> BACKSLASH DOT','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',64),
  ('expr -> BACKSLASH STAR','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',65),
  ('expr -> BACKSLASH PLUS','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',66),
  ('expr -> BACKSLASH QUESTION','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',67),
  ('expr -> BACKSLASH BAR','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',68),
  ('expr -> BACKSLASH LPAREN','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',69),
  ('expr -> BACKSLASH RPAREN','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',70),
  ('expr -> BACKSLASH BACKSLASH','expr',2,'p_escape','/Users/seojunkyo/Desktop/automata/regex.py',71),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','/Users/seojunkyo/Desktop/automata/regex.py',77),
  ('expr -> expr STAR','expr',2,'p_expr_star','/Users/seojunkyo/Desktop/automata/regex.py',82),
  ('expr -> expr PLUS','expr',2,'p_expr_plus','/Users/seojunkyo/Desktop/automata/regex.py',87),
  ('expr -> expr QUESTION','expr',2,'p_expr_question','/Users/seojunkyo/Desktop/automata/regex.py',93),
  ('expr -> expr expr','expr',2,'p_expr_chain','/Users/seojunkyo/Desktop/automata/regex.py',99),
  ('expr -> DOT','expr',1,'p_expr_dot','/Users/seojunkyo/Desktop/automata/regex.py',104),
  ('expr -> ALPHA','expr',1,'p_expr_alpha','/Users/seojunkyo/Desktop/automata/regex.py',113),
  ('expr -> expr BAR expr','expr',3,'p_expr_bar','/Users/seojunkyo/Desktop/automata/regex.py',118),
]
